config/routes.rb
Rails.application.routes.draw do
  root "sessions#login"
  get "index", to: "articles#index"
  # myindex "articles#myindex"
  get "myindex", to: "articles#myindex"

  get "signup", to: "users#new"
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get "login", to: "sessions#login"
  post "login", to: "sessions#create"
  post "logout", to: "sessions#destroy"
  get "logout", to: "sessions#logout"


  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 3 }
   

    VALID_STATUSES = ['public', 'private', 'archived']

    validates :status, inclusion: { in: VALID_STATUSES }
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

  def archived?
    status == 'archived'
  end
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end
    class_methods do
        def public_count
          where(status: 'public').count
        end
      end
    def archived?
      status == 'archived'
    end
  end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def set_no_cache
        response.headers['Cache-Control'] = 'no-cache, no-store,
                                            max-age=0, must-revalidate'
        response.headers['Pragma'] = 'no-cache'
        response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
      end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # http_basic_authenticate_with name: "hi", password: "hi", except: [:index, :show]

  def index
    @articles = Article.all
    # @articles = Article.where(userid: 1)
  end
  def myindex
    # @articles = Article.all
    @articles = Article.where(userid: session[:user_id])
  end

  def show
    @article = Article.find(params[:id])
    # @article = Article.find_by(userid: params[:userid])
    # @article = Article.where(userid: params[:user_id])
    # @article = Article.where( userid: 2 )
  end
  def myshow
    @article = Article.find(params[:id])
    # @article = Article.find_by(userid: params[:userid])
    # @article = Article.where(userid: params[:user_id])
    # @article = Article.where( userid: 2 )
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

    private
    def article_params
      params.require(:article).permit(:title, :body, :status).merge({userid: session[:user_id]})
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # http_basic_authenticate_with name: "hi", password: "hi", only: :destroy

    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
    end

    private
      def comment_params
        params.require(:comment).permit( :body, :status).merge({commenter: session[:user_name]})
      end
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by(username: params[:username])
        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            session[:user_name] = @user.username
            
            redirect_to index_path
        else
            message="something went wrong ! incorrect"
            redirect_to login_path, notice: message
        end
    end

    def destroy
        
        session.delete(:user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end
    def show
        @user = User.find(params[:id])
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @create_user ||=user.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="center">
<article class="leaderboard">
  <header><center>
<%= form_with model: article do |form| %>
     
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    
  
    <div>
      <%= form.submit %>

    </div>
     <div class="hidden" >
    <%= form.label :status %><br>
     <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
   </div>
  <% end %>
  </center>
  </header>
  </article>


  
<style>
.vertical-center-index {
    margin: 0;
    position: absolute;
    
    top: 20%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }

  // bare minimuu styles
body {
  margin: 0;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
}

.leaderboard {
  box-shadow: 0 0 40px -10px rgba(0, 0, 0, .4);
}





.leaderboard {
  max-width: 490px;
  width: 100%;
  border-radius: 12px;
}
</style>

app/views/articles/edit.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center-index">
<center><h1 class="w3-container w3-cursive"> Edit Article</h1></center>

<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "Back", index_path %>
</div>
</body>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center-index">
<center><h1 class="w3-container w3-cursive">HomePage<h1></center>

 <!--Our blog has <%#= Article.public_count #%> articles and counting!
 Our session has <%#= session[:user_id] #%> ! -->


<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "Add Ads", new_article_path %>
</div>
<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "show my Ads", myindex_path %>
</div>

<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "Logout", logout_path %>
</div>
</div>
</div>
</body>



<div class="vertical">
<div class="boot">
<article class="leaderboard">
<article class="leaderboard">
 
  <header><center>
  <h2 class="w3-container w3-cursive">Ads which are Published</h2>
  </center></header>
  </article>
  <article class="leaderboard">
<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
    <li>
       <%= link_to article.title, article %>
    </li>
    <% end %>
  <% end %>
</ul>
</article>
</article>
</div>
</div>





<style>
.vertical-center-index {
    margin: 0;
    position: absolute;
    
    top: 20%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }

  // bare minimuu styles
body {
  margin: 0;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
}

.leaderboard {
  box-shadow: 0 0 40px -10px rgba(0, 0, 0, .4);
}

.boot{
margin: auto;
width: 50%;
padding: 10px;
}
@media only screen and (max-width:1006px){
  .boot{
  margin-left: auto;
margin-right: auto;
margin-top:50px;
width: 50%;
padding: 10px;
}
}
@media only screen and (max-width:600px){
  .boot{
  margin-left: auto;
margin-right: auto;
margin-top:100px;
width: 50%;
padding: 10px;
}
body {
  margin: auto;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
  
}
.vertical-center-index {
    margin-left: -100px;
    position: absolute;
    
    top: 20%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }
}

ul {
  line-height: 2.2;
}

ul li {
  list-style-type: none;
  counter-increment: item;
}

ul li:before {
  content: counter(item);
  display: inline-block;
  width: 12px;
  height: 20px;
  font-family: "Indie Flower", cursive;
  margin-right: 5px;
  background-color: #f9dd94;
  color: #7eb4e2;
  font-weight: bold;
  font-size: 140%;
  padding: 0 8px 8px;
  border-radius: 3px;
  line-height: 1.3;
}


.leaderboard {
  max-width: 490px;
  width: 100%;
  border-radius: 12px;
}
</style>

app/views/articles/myindex.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center-index">
<center><h1 class="w3-container w3-cursive">My Ads</h1></center>

<!-- Our blog has <%#= Article.public_count #%> articles and counting!
# Our session has <%#= session[:user_id] #%> ! -->

<div style="color: black;

text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "Add Ads", new_article_path %>
</div>

<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "back", index_path %>
</div>

</div>
</div>
</body>


<div class="vertical">
<div class="boot">
<article class="leaderboard">
<article class="leaderboard">
 
  <header><center>
  <h2 class="w3-container w3-cursive">My Ads</h2>
  </center></header>
</article>
<article class="leaderboard">
<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
     <li>
       <%= link_to article.title,article %>
     </li>
    <% end %>
  <% end %>
</ul>
</article>
</article>
</div>
</div>




<style>
.vertical-center-index {
    margin: 0;
    position: absolute;
    
    top: 20%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }

  // bare minimuu styles
body {
  margin: 0;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
  
}

.leaderboard {
  box-shadow: 0 0 40px -10px rgba(0, 0, 0, .4);
}

.boot{
margin: auto;
width: 50%;
padding: 10px;
}
@media only screen and (max-width:1006px){
  .boot{
  margin-left: auto;
margin-right: auto;
margin-top:50px;
width: 50%;
padding: 10px;
}
}
@media only screen and (max-width:600px){
  .boot{
  margin-left: auto;
margin-right: auto;
margin-top:100px;
width: 50%;
padding: 10px;
}
body {
  margin: auto;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
  
}
.vertical-center-index {
    margin-left: -80px;
    position: absolute;
    
    top: 20%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }

}



ul {
 
  line-height: 2.2;
}

ul li {
  
  list-style-type: none;
  counter-increment: item;
}

ul li:before {
  content: counter(item);
  display: inline-block;
  width: 12px;
  height: 20px;
  font-family: "Indie Flower", cursive;
  margin-right: 5px;
  background-color: #f9dd94;
  color: #7eb4e2;
  font-weight: bold;
  font-size: 140%;
  padding: 0 8px 8px;
  border-radius: 3px;
  line-height: 1.3;
}


.leaderboard {
  max-width: 490px;
  width: 100%;
  border-radius: 12px;
}
</style>

app/views/articles/myshow.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>
<%#= render @article.comments %>
<% @article.comments.each do |comment| %>
  <p>
    <strong><%= comment.commenter %>:</strong>
    

    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/articles/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center-index">
<center><h1 class="w3-container w3-cursive"> New Ads</h1></center>

<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
<%= link_to "Back", index_path %>
</div>
</body>
<%= render "form", article: @article %>






<style>


  // bare minimuu styles
body {
  margin: 0;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
}

.leaderboard {
  box-shadow: 0 0 40px -10px rgba(0, 0, 0, .4);
}


.leaderboard {
 
  width: 150%;
  border-radius: 12px;
}

app/views/articles/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center-index">
<center><h1 class="w3-container w3-cursive"><h1><%= @article.title %></h1></center>



<% if @article.userid == session[:user_id] %>

<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
  <%= link_to "Edit", edit_article_path(@article) %>
</div>

<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
  <%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
   

<% end %>
</div>
<div style="color: black;
padding: 3px 5px;
text-align: center;
text-decoration: none;
display: inline-block;">
  <%= link_to "Back", index_path %>
</div>
</div>
</body>


<div class="center">

<article class="leaderboard">
 
  <header>
  <h3 class="w3-container w3-cursive">Article Description</h3>
  <p class="w3-container w3-cursive"><%= @article.body %></></header>
  </article>

  <article class="leaderboard">
  <header><ul>
  <h5 class="w3-container w3-cursive"><b>Add a comment:</b></h5>
  <%= render 'comments/form' %>
  
  <h5 class="w3-container w3-cursive"><b>Comments</b></h5>
<%#= render @article.comments %>
<% @article.comments.each do |comment| %>
  <p>
    <strong><%= comment.commenter %></strong>
    

    <%= comment.body %>
  </p>
<% end %>

</ul>
</header>
</article>
</div>


<style>

  // bare minimuu styles
body {
  margin: 0;
  background-color: #eaeaea;
  display: grid;
  height: 100vh;
  place-items: center;
  font-family: 'Source Sans Pro', sans-serif;
}

.leaderboard {
  box-shadow: 0 0 40px -10px rgba(0, 0, 0, .4);
}

.leaderboard {
  max-width: 490px;
  width: 100%;
  border-radius: 12px;
}


ul {
  line-height: 2.2;
}

ul li {
  list-style-type: none;
  counter-increment: item;
}

ul li:before {
  content: counter(item);
  display: inline-block;
  width: 12px;
  height: 20px;
  font-family: "Indie Flower", cursive;
  margin-right: 5px;
  background-color: #f9dd94;
  color: #7eb4e2;
  font-weight: bold;
  font-size: 140%;
  padding: 0 8px 8px;
  border-radius: 3px;
  line-height: 1.3;
}
</style>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    
    <p>
      <%#= form.label :body #%><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
    <p>
    <div class="hidden">
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %> </div>
</p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html copy.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center">
   <center>
<h1 style="color:orange">SignUp</h1>
<%= form_for @user do |f| %>
    <p class="w3-large" style="color:white">username </p>
    <%= f.text_field :username %>
    <p class="w3-large" style="color:white">password </p>
    <%= f.password_field :password %><br><br>
    </center>
    <%= f.submit "SignUp " %>&emsp;
    <%= link_to "LogIn", root_path %>
<% end %>
</div>
</div>
</body>

<style>
body, h2{
    background-image: url("/assets/cartoon.jpg") ;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;

    font-family: "Courier New", monospace;     
}

</style>

app/views/users/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container w3-cursive">
<div class="vertical-center">
<div class="horizental-center">
   
<center> <h1 style="color:orange">Sign Up</h1> </center>
<%= form_for @user do |f| %>
    <center>
    <p class="w3-large" style="color:white">username </p>
    <%= f.text_field :username %>
    <p class="w3-large" style="color:white">password </p>
    <%= f.password_field :password %><br><br>
    </center>
    <%= f.submit "SignUp " %>&emsp;
    <div style="background-color: white;
        color: black;
        padding: 3px 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;">
    <%= link_to "LogIn", root_path %>
    </div>
<% end %>
</div>
</div>
</div>
</body>

<style>
body, h2{
    background-image: url("https://bharathiraja-blog.000webhostapp.com/images/cartoon.jpeg") ;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;

    font-family: "Courier New", monospace;     
}
h1{
  font-family: "Indie Flower", cursive; 
}

</style>